# Project information
site_name: QGIS Model Baker
site_description: >-
  This site contains documentation about QGIS Model Baker

# Repository
repo_name: opengisch/QgisModelBaker
repo_url: https://github.com/opengisch/QgisModelBaker
edit_uri: https://github.com/opengisch/QgisModelBaker/tree/master/docs/

# Theme configuration
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Page tree
nav:
  - Home: index.md
  - User Guide:
    - Get Started: user_guide/get_started.md
    - Model and Data Import Workflow: user_guide/import_workflow.md
    - Export Data Workflow: user_guide/export_workflow.md
    - Validate Data: user_guide/validation.md
    - Plugin Configuration: user_guide/plugin_configuration.md
  - Tipps & Tricks:
    - Meta Attributes: background_info/meta_attributes.md
    - UsabILIty Hub: background_info/usabilityhub.md
    - Basket and Dataset Handling: background_info/basket_handling.md
    - Relations in QGIS: background_info/relations.md
    - Upgrade ili2db 3 to 4: background_info/upgrade_3_to_4.md
  #- Library: Info about the upcoming python package
  - Development: development.md

markdown_extensions:
  - attr_list
  - def_list
  - admonition
