name: doc
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/doc.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python requirements
        run: pip install -r ./docs/.utils/requirements.txt

      - name: Install Transifex client
        run: |
          curl -OL https://github.com/transifex/cli/releases/download/v1.3.1/tx-linux-amd64.tar.gz
          tar -xvzf tx-linux-amd64.tar.gz

      - name: Configure Transifex
        run: |
          python ./docs/.utils/transifex_utils.py
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}

      - name: Push source files to Transifex
        run: |
          ./tx push
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}

      - name: Pull translations from Transifex
        run: |
          ./tx pull --translations --all --minimum-perc 10
          ./tx status
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}

      - name: Build docs
        run: mkdocs gh-deploy --force
        env:
          DEFAULT_LANGUAGE_ONLY: false
